log_level: INFO
anonymization:
  class_ids: [0, 2, 3, 5, 7]
  blur_strength: 0.15
  jpeg_quality: 90
redis:
  host: redis
  port: 6379
  stream_id: stream1
  input_stream_prefix: objecttracker
  output_stream_prefix: frameanonymizer
prometheus_port: 8000
